// Copyright 2023 QMK
// SPDX-License-Identifier: GPL-2.0-or-later

#include "jrecyclebin.h"

const key_override_t delete_key_override = ko_make_basic(MOD_MASK_SHIFT, KC_BSPC, KC_DEL);
const key_override_t semicolon_key_override = ko_make_basic(MOD_MASK_SHIFT, KC_COLN, KC_SCLN);

bool process_record_user(uint16_t keycode, keyrecord_t *record) {
    switch (keycode) {
        case DANCER:
            SEND_STRING(SS_LALT("D83D+DC83"));
            return false;
        EMOTE(UH);
        EMOTE(FROG);
        EMOTE(HI_WAVE);
        EMOTE(CRIKEY);
        EMOTE(DAMN);
        EMOTE(TIGHT);
        EMOTE(CLOWN);
        EMOTE(TADA);
        EMOTE(ZZZ);
        EMOTE(POINT_RIGHT);
        EMOTE(JOY);
        EMOTE(LOVE);
        EMOTE(KILLED);
        EMOTE(POINT_LEFT);
        EMOTE(QUIET);
        EMOTE(FROG_AAH);
        EMOTE(NO);
        EMOTE(HAND_THUMB_DOWN);
        EMOTE(HAND_THUMB_UP);
        EMOTE(JABSCO);
        EMOTE(FROG_OOO);
        EMOTE(NINE);
        EMOTE(BIRDIE);
        EMOTE(MMM);
        EMOTE(FIRE);
        EMOTE(DAFUQ);
        EMOTE(NEUTRAL_FACE);
        EMOTE(SMILE);
        EMOTE(POOP);
        EMOTE(ATTN);
        EMOTE(EXIT);
        EMOTE(REDONK);
        EMOTE(VICTORY);
        EMOTE(ERNIE);
        EMOTE(WOWEE);
        EMOTE(YIKES);
        EMOTE(GOOD_GAME);
        EMOTE(HAND_CLAP);
        EMOTE(FROG_SAD);

        JP(A);
        JP(I);
        JP(U);
        JP(E);
        JP(O);
        JP(KA);
        JP(GA);
        JP(KI);
        JP(GI);
        JP(KU);
        JP(GU);
        JP(KE);
        JP(GE);
        JP(KO);
        JP(GO);
        JP(SA);
        JP(ZA);
        JP(SHI);
        JP(JI);
        JP(SU);
        JP(ZU);
        JP(SE);
        JP(ZE);
        JP(SO);
        JP(ZO);
        JP(TA);
        JP(DA);
        JP(CHI);
        JP(DI);
        JP(TSU);
        JP(DZU);
        JP(SMALL_TSU);
        JP(TE);
        JP(DE);
        JP(TO);
        JP(DO);
        JP(NA);
        JP(NI);
        JP(NU);
        JP(NE);
        JP(NO);
        JP(HA);
        JP(BA);
        JP(PA);
        JP(HI);
        JP(BI);
        JP(PI);
        JP(FU);
        JP(BU);
        JP(PU);
        JP(HE);
        JP(BE);
        JP(PE);
        JP(HO);
        JP(BO);
        JP(PO);
        JP(MA);
        JP(MI);
        JP(MU);
        JP(ME);
        JP(MO);
        JP(YA);
        JP(YU);
        JP(YO);
        JP(SMALL_YA);
        JP(SMALL_YU);
        JP(SMALL_YO);
        JP(RA);
        JP(RI);
        JP(RU);
        JP(RE);
        JP(RO);
        JP(WA);
        JP(WI);
        JP(WE);
        JP(WO);
        JP(N);
        JP(SMALL_A);
        JP(SMALL_I);
        JP(SMALL_U);
        JP(SMALL_E);
        JP(SMALL_O);
        JP(SMALL_KE);
        JP(SMALL_WA);
    }
    return true;
}
